routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserInformationController@create');
Route::get('users/export-csv', 'UserInformationController@generateCsv');
Route::resource('/users', 'UserInformationController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/UserInformation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserInformation extends Model
{
    protected $fillable=['name','gender','phone','email_id','address','nationality','dob','preferred_contact'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserInformationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserInformationRequest;
use App\UserInformation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;

class UserInformationController extends Controller
{
    public function index()
    {
        $users = UserInformation::all();
        if (sizeof($users) == 0) {
            return redirect('users/create',compact('users'));
        } else {
            $users = UserInformation::paginate(10);
            return view('user.index', compact('users'));


        }
    }

    public function store(UserInformationRequest $request)
    {
        if ($request->all()) {
            UserInformation::create($request->all());
            session()->flash('success', 'Successfully added user Information');
            return redirect('users');
        }

    }

    public function create()
    {
        $users = UserInformation::all();
        /* Set the $timezone variable to become the current timezone */
        date_default_timezone_set('Asia/Kathmandu');
        /* This sets the $time variable to the current hour in the 24 hour clock format */
        $time = date("H");

        /* If the time is less than 1200 hours, show good morning */
        if ($time < "12") {
            $greeting = "Good morning";
        } else
            /* If the time is grater than or equal to 1200 hours, but less than 1700 hours, so good afternoon */
            if ($time >= "12" && $time < "17") {
                $greeting = "Good afternoon";
            } else
                /* Should the time be between or equal to 1700 and 1900 hours, show good evening */
                if ($time >= "17") {
                    $greeting = "Good evening";
                }
        return view('user.add', compact('greeting','users'));
    }

    public function generateCsv()
    {
        $headers = array(
            'Content-Type' => 'application/vnd.ms-excel; charset=utf-8',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Content-Disposition' => 'attachment; filename=abc.csv',
            'Expires' => '0',
            'Pragma' => 'public',
        );

        $filename = "download.csv";
        $handle = fopen($filename, 'w');
        fputcsv($handle, [
            "id",
            "name"
        ]);

        DB::table("user_informations")->orderBy('id','desc')->chunk(100, function ($data) use ($handle) {
            foreach ($data as $row) {
                // Add a new row with data
                fputcsv($handle, [
                    $row->id,
                    $row->name
                ]);
            }
        });


        fclose($handle);

        return Response::download($filename, "download.csv", $headers);
    }
}

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>User Information</title>


    <link rel="apple-touch-icon" sizes="57x57" href="{{url('assets/icon/apple-icon-57x57.png')}}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{url('assets/icon/apple-icon-60x60.png')}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{url('assets/icon/apple-icon-72x72.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{url('assets/icon/apple-icon-76x76.png')}}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{url('assets/icon/apple-icon-114x114.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{url('assets/icon/apple-icon-120x120.png')}}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{url('assets/icon/apple-icon-144x144.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{url('assets/icon/apple-icon-152x152.png')}}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url('assets/icon/apple-icon-180x180.png')}}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{{url('assets/icon/android-icon-192x192.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url('assets/icon/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{url('assets/icon/favicon-96x96.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url('assets/icon/favicon-16x16.png')}}">
    <link rel="manifest" href="{{url('assets/icon/manifest.json')}}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">



    <meta name="description" content="User Information">
    <meta name="keywords" content="User Information">

    <link rel="stylesheet" href="{{url('assets/css/bootstrap/bootstrap.css')}}">

    <link rel="stylesheet" href="{{url('assets/fonts/fontawesome/css/font-awesome.min.css')}}">


    <link rel="stylesheet" href="{{url('assets/css/helpers.css')}}">
    <link rel="stylesheet" href="{{url('assets/css/style.css')}}">
</head>
<body data-spy="scroll" data-target="#pb-navbar" data-offset="200">

<!-- END nav -->
@yield('content')

<footer class="pb_footer bg-light" role="contentinfo">
    <div class="container">
        <div class="row text-center">
            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="{{url('/')}}" class="p-2"><i class="fa fa-facebook fa-2x"></i></a></li>
                    <li class="list-inline-item"><a href="{{url('')}}" class="p-2"><i class="fa fa-twitter fa-2x"></i></a></li>
                    <li class="list-inline-item"><a href="{{url('/')}}" class="p-2"><i class="fa fa-linkedin fa-2x"></i></a></li>
                </ul>
            </div>
        </div>

    </div>
</footer>

<script src="{{url('assets/js/bootstrap.min.js')}}"></script>

@yield('js')
</body>
</html>

resources/views/user/add.blade.php
@extends('layout.master')

@section('content')
    <section
            class="pb_cover_v3 overflow-hidden cover-bg-indigo cover-bg-opacity text-left pb_gradient_v1"
            id="section-home">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-4">
                    <h1 class="mb-3" style="color: white">{{$greeting}}</h1>

                    <div class="sub-heading">
                        <p class="mb-4">{{gethostname()}}</p>
                        <p class="mb-5">
                            @if(count($users)!=0)
                                <a class="btn btn-success btn-lg pb_btn-pill smoothscroll"
                                           href="{{url('users')}}"><span
                                        class="pb_font-14 text-uppercase pb_letter-spacing-1">View Users</span></a>

                            @endif
                        </p>
                    </div>
                </div>

                <div class="col-md-8 relative align-self-center">

                    <form action="{{route('users.store')}}" class="bg-white rounded pb_form_v1" name="user_form"
                          onsubmit="return validateForm()" method="post">
                        {{csrf_field()}}
                        <h2 class="mb-4 mt-0 text-center">Add New User Information</h2>
                        <div class="form-row">
                            <div class="col">
                                <div class="form-group">
                                    <input type="text" name="name" class="form-control pb_height-50 reverse"
                                           placeholder="Full name" value="{{old('name')}}">
                                    {!! $errors->first('name', '<span class="text-danger">:message</span>') !!}
                                </div>
                            </div>
                            <div class="col">

                                <div class="form-group">
                                    <input type="text" name="address" class="form-control pb_height-50 reverse"
                                           placeholder="Address" value="{{old('address')}}">
                                    {!! $errors->first('address', '<span class="text-danger">:message</span>') !!}

                                </div>

                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col">
                                <div class="form-group">
                                    <input type="text" name="nationality" class="form-control pb_height-50 reverse "
                                         id="nationality"  placeholder="Nationality" value="{{old('nationality')}}">
                                    {!! $errors->first('nationality', '<span class="text-danger">:message</span>') !!}

                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <input type="date" name="dob" id="dob" class="form-control pb_height-50 reverse"
                                                                              placeholder="Date of Birth" value="{{old('dob')}}">
                                    {!! $errors->first('dob', '<span class="text-danger">:message</span>') !!}

                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-control reverse">
                                <label>Gender:</label>&nbsp;

                                <input type="radio" class="reverse mp-2 ml-4" name="gender" value="M"<?php if(old('gender')=='M') echo "checked";?> >&nbsp; Male &nbsp;
                                <input type="radio" class="reverse mp-2 ml-4 " name="gender" value="F" <?php if(old('gender')=='F') echo "checked";?>>&nbsp; Female &nbsp;
                                <input type="radio" class="reverse mp-2 ml-4" name="gender" value="O"<?php if(old('gender')=='O') echo "checked";?>>&nbsp; Other


                            </div>
                            {!! $errors->first('gender', '<span class="text-danger">:message</span>') !!}
                        </div>
                        <div class="form-row">
                            <div class="col">
                                <div class="form-group">
                                    <input type="email" name="email_id" class="form-control pb_height-50 reverse"
                                           placeholder="Email" value="{{old('email_id')}}">
                                    {!! $errors->first('email_id', '<span class="text-danger">:message</span>') !!}

                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <input type="text" name="phone" class="form-control pb_height-50 reverse"
                                           placeholder="Phone Number format 01-5555815" value="{{old('phone')}}">
                                    {!! $errors->first('phone', '<span class="text-danger">:message</span>') !!}

                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="pb_select-wrap">
                                <select name="preferred_contact" class="form-control pb_height-50 reverse">
                                    <option value="{{old('preferred_contact')}}" selected>Preferred Contact</option>
                                    <option value="phone">Phone</option>
                                    <option value="email">Email</option>


                                </select>
                                {!! $errors->first('preferred_contact', '<span class="text-danger">:message</span>') !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit"
                                   class="btn btn-primary btn-lg btn-block pb_btn-pill  btn-shadow-blue"
                                   value="Register">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
    <!-- END section -->



@endsection
@section('js')

    <script>
        //frontend Validation
        function validateForm() {
            var name = document.forms["user_form"]["name"].value;
            var address = document.forms["user_form"]["address"].value;
            var email_id = document.forms["user_form"]["email_id"].value;
            var phone = document.forms["user_form"]["phone"].value;
            var dob = document.forms["user_form"]["dob"].value;
            if (name == "") {
                alert("Name must be filled out");
                return false;
            }
            if (address == "") {
                alert("Address must be filled out");
                return false;
            }
            if (email_id == "") {
                alert("Email Address must be filled out");
                return false;
            }
            if (phone == "") {
                alert("Phone Number must be filled out");
                return false;
            }
            if (dob == "") {
                alert("Date of Birth must be filled out");
                return false;
            }
        }


    </script>



@endsection

resources/views/user/index.blade.php
@extends('layout.master')
@section('content')
    <section class=" pb_section pb_slant-reverse p-5">

        <div class="container rounded pb_form_v1" >


            @if (Session::has('success'))
                <div class="alert alert-success">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ Session::get('success') }}
                </div>
            @endif
            <div class="row justify-content-center mb-0">
                <div class="col-md-6 text-center mb-2">
                    <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-12 pb_letter-spacing-2"><strong><i class="fa fa-users"></i> User Information</strong>
                    </h5>

                </div>

            </div>

            <div class="row">
                <div class="col-md">
                    <a href="{{url('users/export-csv')}}" class="pull-right p-1 text-success" data-toggle="tooltip" title="Export"><i class="fa fa-file-excel-o fa-2x"></i></a>

                    <a href="{{route('users.create')}}" target="_blank" class="pull-right p-1" data-toggle="tooltip" title="Add Users"><i class="fa fa-plus-circle fa-2x"></i></a>
                    <div  class="pb_accordion" data-children=".item">
                        <table class="table table-responsive table-bordered">
                            <thead>
                            <tr>
                                <th>S.N</th>
                                <th>Full Name/Contact</th>
                                <th>Gender/Date of Birth</th>
                                <th>Address/Nationality</th>

                                <th>Preferred Contact</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $key=>$user)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>
                                        <i class="fa fa-user"></i>&nbsp;{{ucfirst($user->name)}}
                                        <br>
                                        <i class="fa fa-envelope"> </i>&nbsp;{{$user->email_id}}<br>
                                        <i class="fa fa-phone"> </i>&nbsp;{{$user->phone}}
                                    </td>
                                    <td>
                                        @if($user->gender=="M")
                                            <i class="fa fa-male"> Male</i>
                                        @elseif($user->gender=="F")
                                            <i class="fa fa-male"> Female</i>

                                        @else
                                            <i class="fa fa-transgender"> Other</i>

                                        @endif
                                        <br>
                                        <i class="fa fa-birthday-cake">  {{$user->dob}}</i>
                                    </td>
                                    <td>
                                     <i class="fa fa-location-arrow"></i>   {{ucfirst($user->address)}}<br>
                                       <i class="fa fa-flag"></i> {{ucfirst($user->nationality)}}
                                    </td>
                                    <td class="text-center">
                                        @if($user->preferred_contact=="phone")
                                            <span class="pb-icon pb_color-primary">  <i
                                                        class=" fa fa-phone-square fa-3x">&nbsp;</i></span>

                                        @else
                                            <span class="pb_color-success">  <i class="fa fa-envelope fa-3x">&nbsp;</i></span>

                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>












    </section>
    <!-- END section -->




@endsection